// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNXsfI2FKYGMqnLDjrwHBf5yzvrKB3c3U',
    appId: '1:382143581446:web:5d6d01037237d890ea6287',
    messagingSenderId: '382143581446',
    projectId: 'abrar-khira-portfolio',
    authDomain: 'abrar-khira-portfolio.firebaseapp.com',
    storageBucket: 'abrar-khira-portfolio.firebasestorage.app',
    measurementId: 'G-T8VNLC9YRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4J39gFLm9E5A2cbfHxSL8vHEeMMJkSa0',
    appId: '1:382143581446:android:e5d948b6720e1a01ea6287',
    messagingSenderId: '382143581446',
    projectId: 'abrar-khira-portfolio',
    storageBucket: 'abrar-khira-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00zAxEUW0tOMu7elx2D9jlLuFj2R4ODE',
    appId: '1:382143581446:ios:66e230b730e77374ea6287',
    messagingSenderId: '382143581446',
    projectId: 'abrar-khira-portfolio',
    storageBucket: 'abrar-khira-portfolio.firebasestorage.app',
    iosBundleId: 'com.abrarportfolio.abrarPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNXsfI2FKYGMqnLDjrwHBf5yzvrKB3c3U',
    appId: '1:382143581446:web:aa7d69f0c52ab485ea6287',
    messagingSenderId: '382143581446',
    projectId: 'abrar-khira-portfolio',
    authDomain: 'abrar-khira-portfolio.firebaseapp.com',
    storageBucket: 'abrar-khira-portfolio.firebasestorage.app',
    measurementId: 'G-C5BEG33X2X',
  );
}
